# Meta Data for SEO

## Homepage
title = "Chatcontrole"
titleSeparator = "|"
titleAddition = "Je privéberichten gaan gescand worden"
description = "Het is a Hugo theme for building secure, fast, and SEO-ready documentation websites, which you can easily update and customize."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["chatcontrole.png"]
ogLocale = "nl_NL"
domainTLD = "chatcontrole.nl"
titleHome = "Chatcontrolee"

## Twitter Cards
twitterSite = "Chatcontrole"
twitterCreator = "Chatcontrole"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Chatcontrole"
schemaAuthor = "Chatcontrole"
schemaLocale = "nl-NL"
schemaLogo = "chatcontrole.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "chatcontrole.png"
schemaImageWidth = 1280
schemaImageHeight = 640

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "chatcontrole.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Website gebouwd met <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> en <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Kopieëerlinks/<a class=\"text-muted\" href=\"https://www.gnu.org/licenses/copyleft.nl.html\">auteursplicht</a>"

# Alert
alert = false
alertDismissable = true

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/csmeyns/chatcontrole"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

[sections]
  sectionNav = []

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = true
  navbarSticky = true
  toTopButton = true
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = false
